import type { Metadata } from "next";
import "./globals.css";
import Menu from "@/components/menu/Menu";
import Footer from "@/components/Footer";
import { CartContextProvider } from "@/contexts/CartContext";

export const metadata: Metadata = {
  title: "وبسایت فروشگاهی",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CartContextProvider>
      <html lang="fa">
        <body className={`bg-gray-200 antialiased`}>
          <Menu />
          {children}
          <Footer />
        </body>
      </html>
    </CartContextProvider>
  );
}
